language: go

go:
  - "1.5.1"
install:
  - "go get"
  - "go get github.com/franela/goblin"
  - "go get github.com/go-gomail/gomail"
script:
  - "go env"
  - "go test -v ./..."
before_install:
  - pip install --user codecov
after_success:
  - codecov